title = "My New Hugo Site"
baseURL = "http://example.org/"
languageCode = "en-us"
theme = "gohugo-default"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]

  description = "The last theme you'll ever need. Maybe."
