title = "My New Hugo Site"
baseURL = "http://gohugo-default-theme.surge.sh"
languageCode = "en-us"
theme = "gohugo-default-theme"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 18
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]

  description = "The last theme you'll ever need. Maybe."
